import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'index',
    'contributing',
    'disclaimer',
    'tech-faq',
    {type: 'category', label: 'General Factsheets', items: [
    {
      type: 'autogenerated',
      dirName: 'general',
    }
    ]},
    {
      type: 'category',
      label: 'Climate Resilience',
      link: { type: 'doc', id: 'climate-resilience/index' }, 
      items: [
        {
          type: 'category',
          label: 'Introduction',
          items: [
            'climate-resilience/Introduction/intro', 
            'climate-resilience/Introduction/solutions-resilience', 
            'climate-resilience/Introduction/opportunities', 
            'climate-resilience/Introduction/challenges', 
          ],
        },
        {
          type: 'category',
          label: 'Factsheets',
          items: [
            'climate-resilience/fact-sheets-cres/ai', 
            'climate-resilience/fact-sheets-cres/data-sources', 
            'climate-resilience/fact-sheets-cres/digital-twins', 
            'climate-resilience/fact-sheets-cres/communication', 
            'climate-resilience/fact-sheets-cres/mobile-tools',
            'climate-resilience/fact-sheets-cres/rmis-cres',
            'climate-resilience/fact-sheets-cres/iot', 
          ],
        },
        'climate-resilience/integration',
      ],
    },
  ],
};

export default sidebars;
